name: Scheduled Cast

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
  workflow_dispatch:      # This allows manual triggering of the workflow

jobs:
  send-cast:
    runs-on: ubuntu-latest
    environment: scheduling  # Specify the environment where the secrets are stored
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run the cast script
        run: npm run send-cast
        env:
          FIREBASE_PROJECT_ID: ${{ vars.FIREBASE_PROJECT_ID }}
          FIREBASE_PRIVATE_KEY_ID: ${{ secrets.FIREBASE_PRIVATE_KEY_ID }}
          FIREBASE_PRIVATE_KEY: ${{ secrets.FIREBASE_PRIVATE_KEY }}
          FIREBASE_CLIENT_EMAIL: ${{ secrets.FIREBASE_CLIENT_EMAIL }}
          FIREBASE_TYPE: ${{ secrets.FIREBASE_TYPE }}
          WARPCAST_PRIVATE_KEY: ${{ secrets.WARPCAST_PRIVATE_KEY }}
          WARPCAST_FID: ${{ secrets.WARPCAST_FID }}
          NEYNAR_API: ${{ secrets.NEYNAR_API }}  # Neynar API Key
          NEYNAR_SIGNER: ${{ secrets.NEYNAR_SIGNER }}  # Signer ID for casting
          EMPOWER_CHANNEL_URL: ${{ secrets.EMPOWER_CHANNEL_URL }}  # URL for the empower channel
          NEXT_PUBLIC_BASE_PATH: ${{ secrets.NEXT_PUBLIC_BASE_PATH }}  # Base path for generating shareable URLs
          Hub_gRPC_URL: ${{ secrets.Hub_gRPC_URL }}  # Farcaster Hub gRPC URL if needed
          Hub_HTTP_URL: ${{ secrets.Hub_HTTP_URL }}  # Farcaster Hub HTTP URL if needed
